Ignored WalterBTest due to failing:
getPage(WalterBTest)  Time elapsed: 10.277 sec  <<< FAILURE!
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='editorial_block_center']/h1"}